version: "3.9"
services:

  mysql_service:
    container_name: mysql_service
    build: ./database
    ports:
      - "6603:3306"
  
  api_service:
    container_name: api_service
    build: ./api
    depends_on:
      - mysql_service
    ports:
      - "9000:8000"
    volumes:
      - ./api:/api

  crawl_service:
    container_name: crawl_service
    build: ./crawl
    depends_on:
      - mysql_service
    ports:
      - "5000:7000"
    volumes:
      - ./crawl:/app

  web_service:
    container_name: web_service
    build: ./web
    depends_on:
      - mysql_service
    ports:
      - "4000:3000"
    volumes:
      - ./web:/app